<template>
  <div>
    <v-dialog
      v-model="dialog"
      max-width="450"
      persistent
    >
      <v-card>
        <v-toolbar flat color="primary">
          <v-card-title class="text-white">Create Coupon</v-card-title>
        </v-toolbar>

        <v-form lazy-validation ref="form" class="pa-4">
          <v-card-text class="text-center">Note: The code is auto generated by the system</v-card-text>
          <v-text-field
            class="mb-n2"
            dense
            outlined
            v-model="form.discount"
            :rules="required"
            type="number"
            placeholder="Enter percentage discount (e.g 15)"
          ></v-text-field>
          <v-text-field
            class="mb-n2"
            dense
            outlined
            v-model="form.user_email"
            :rules="required"
            placeholder="Enter user email"
          ></v-text-field>
          <v-select
            v-model="form.products"
            outlined
            dense
            multiple
            :items="products"
            placeholder="Select products which coupon can be tied to"
            :rules="required"
            :loading="loadingProducts"
          ></v-select>
        </v-form>
        <v-card-actions
          class="d-flex justify-content-end"
        >
          <v-btn
            outlined
            color="error"
            @click="closeModal"
          >Close</v-btn>
          <v-btn
            color="primary"
            elevation="0"
            :loading="loading"
            @click="$refs.form.validate() ? newCoupon() : null"
          >Submit</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<script>
    import { mapActions } from 'vuex';
    import Toasts from "../utils/toast";
    export default {
        props: {
            dialog: {
                Boolean,
                default: false,
            }
        },

        name: "CreateCoupon",
        data() {
            return {
                loading: false,
                form: {},
                required: [(v) => !!v || 'This field is required'],
                products: [],
                toast: new Toasts(),
                loadingProducts: false,
            }
        },

        created() {
            this.getProducts();
        },

        methods: {
            ...mapActions('coupons', [
                'create_coupon'
            ]),

            ...mapActions('products', [
                'get_all_products'
            ]),

            closeModal() {
                this.$parent.dialog = false;
            },

            async getProducts() {
                try {
                    const response = await this.get_all_products();
                    response.data.data.map(item => {
                        let product = {};
                        product.text = item.name;
                        product.value = item.id;

                        this.products.push(product);
                    });
                } catch (error) {
                    this.toast.errorMessage(error);
                }
            },

            async newCoupon() {
                this.loading = true;
                try {
                    const response = await this.create_coupon(this.form);
                    this.toast.successMessage(response);
                    this.loading = false;
                    await this.$parent.getCoupons();
                    this.closeModal();
                    this.$refs.form.reset();
                } catch (error) {
                    this.loading = false;
                    this.toast.errorMessage(error)
                }
            },
        }
    }
</script>

<style scoped>

</style>